@startuml
'https://plantuml.com/sequence-diagram
!include <cloudinsight/kafka>
autonumber
participant Matrix
database MatrixDB
participant SyfterConsumer
queue "<$kafka>" as kafka
participant Syfter
control SyfterSchedule
database SyfterDB
activate kafka
activate Matrix
note over Matrix
Add a device on UI
Associate SyfterId
end note
Matrix -> MatrixDB : Device Onboard
Matrix->kafka : Publish On Topic <device_onboard>
deactivate Matrix
activate Syfter
Syfter <-- kafka : Consume message
note over Syfter
Saving Device Message to MTX_Device
end note
Syfter->SyfterDB : Update on mtx_device/mtx_config
deactivate Syfter
activate SyfterSchedule
SyfterSchedule -> kafka : Inventory/KPI/Alert Topic
deactivate SyfterSchedule
activate SyfterConsumer
SyfterConsumer <- kafka : Inventory/KPI/Alert Topic
SyfterConsumer->MatrixDB : Persist Generic Model
deactivate SyfterConsumer
@enduml